name: Student Copilot API Docker Deployment

on:
  push:
    branches: ["main"]
    
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./server-side

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ${{env.working-directory}}
      run: docker build . -t daniilkan/student-copilot-api:latest
    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the image to Docker Hub
      run: docker push daniilkan/student-copilot-api
